model_list:
  - model_name: gpt-3.5-turbo
    litellm_params:
      model: gpt-3.5-turbo
      api_key: "your-openai-api-key-here"  # Replace with your actual API key
  
  - model_name: gpt-4
    litellm_params:
      model: gpt-4
      api_key: "your-openai-api-key-here"  # Replace with your actual API key

  # Uncomment and configure these if you want to use other models
  # - model_name: claude-3
  #   litellm_params:
  #     model: anthropic/claude-3-sonnet-20240229
  #     api_key: "your-anthropic-api-key-here"
  
  # - model_name: llama2
  #   litellm_params:
  #     model: ollama/llama2
  #     api_base: http://localhost:11434

general_settings:
  completion_model: gpt-3.5-turbo
  max_budget: 100
  budget_duration: 30d

litellm_settings:
  drop_params: true
  set_verbose: false
  request_timeout: 60